name: Daily Login
on:
  workflow_dispatch:
  schedule:
    # JST 10,22
    - cron: "0 0,12 * * *"

jobs:
  daily:
    runs-on: ubuntu-latest
    env:
      data_folder: "data/"

    steps:
      - uses: actions/checkout@v4
      - name: Checkout data repo
        uses: actions/checkout@v4
        with:
          repository: chaldea-center/daily-login-data
          token: ${{ secrets.GH_PAGES_TOKEN }}
          path: ${{ env.data_folder }}

      - name: Save config.json
        run: echo "${{ secrets.CONFIG_DATA }}" | base64 -d > config.json

      - name: Checkout fgoapi
        uses: actions/checkout@v4
        with:
          repository: chaldea-center/fgoapi
          path: fgoapi-repo
          token: ${{ secrets.GH_PAGES_TOKEN }}
      - run: mv fgoapi-repo/fgoapi fgoapi && rm -rf fgoapi-repo

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          sed -i '/^fgoapi/d' requirements.txt && pip install -r requirements.txt
          npm --location=global install js-beautify          

      - name: Login
        run: python main.py
        env:
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Format
        run: sh scripts/format_data.sh

      - name: Commit and publish
        working-directory: ${{ env.data_folder }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git --no-pager diff --stat --staged

          if [ -e $GITHUB_WORKSPACE/commit-msg.txt ]
          then
              git commit -F $GITHUB_WORKSPACE/commit-msg.txt || echo "Nothing to commit"
          else
              git commit -m "$(/bin/date -u "+%Y-%m-%d %H:%M")" || echo "Nothing to commit"
          fi
          git push

  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          time_elapsed: 30
